### ISSUE TITLE
[Progress Bar] - cannot install from anki website code 1/26/2021

### ISSUE THREAD

**Issue by jcdied4me** [glutanimate/progress-bar#1]
## Which add-on is affected? 
Progress Bar

## Prerequisite checklist
[ Please enter an [ x ] character to confirm the points below: ]

- [x] In case of a bug: Have you tried restarting Anki?
- [x] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [x] Did you check the add-on description on AnkiWeb for known issues?
- [x] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?
I would like to be able to install the progress bar in anki

[ Please be as specific as possible. Provide screenshots if you think they can help. ]
![image](https://user-images.githubusercontent.com/7097167/105927747-7804ad80-5ff9-11eb-8e22-83219bbdd477.png)
Used install code provided on the plugin page, added it to the anki add-on's interface, and I receive the above error.

EDIT:
I just downloaded the add-on through the repository on this site and manually installed, but when I restarted Anki I get the following error.
![image](https://user-images.githubusercontent.com/7097167/105930282-3e827100-5ffe-11eb-8871-1609d6233d1d.png)

## Version information

**Anki**
Version ⁨2.1.38 (355e4cd5)
Python 3.8.6 Qt 5.14.2 PyQt 5.14.

**System**
- OS: Windows 10 Pro
- OS Build: 19042.746

**Comment by glutanimate** [comment]
Hey, thanks for the report. The version of Progress Bar that's currently on AnkiWeb does not support newer Anki releases just, yet. However, a fix is already on its way and will be part of the new version of the add-on that will be coming out soon. You can track the progress of the release here: #5
