### ISSUE TITLE
⁨2.1.37 - not suppoeted.

### ISSUE THREAD

**Issue by imaori** [glutanimate/progress-bar#2]
Progress bar - not supported on ver 2.1.37.
https://ankiweb.net/shared/info/2091361802

**Comment by glutanimate** [comment]
Hey, thanks for the report. The version of Progress Bar that's currently on AnkiWeb does not support newer Anki releases just, yet. However, a fix is already on its way and will be part of the new version of the add-on that will be coming out soon. You can track the progress of the release here: #5
