### ISSUE TITLE
[progress bar] understanding a specific setting

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [glutanimate/progress-bar#21]
## Prerequisite checklist
- [ X ] Did you check the add-on description on AnkiWeb for known issues?
- [ X ] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

```
# Only include new cards once reviews are exhausted.
includeNewAfterRevs = True
```
(in line 37)
I don't understand this setting nor the comment above. What is it supposed to do ?
I tried reading the code to understand but I'm not skilled enough :/

edit : also, it seems the "config" button does not work on progress bar in anki 2.1, we have to manually open the python file to edit the settings, just notifying you

## Version information
**Anki 2.1**
**Ubuntu 18.04**

**Comment by glutanimate** [comment]
Hi @thiswillbeyourgithub,

Sorry for the delayed response. Didn't have a lot of time recently.

`includeNewAfterRevs` instructs the Progress Bar add-on to not add new cards to the total tally it counts your progress against until you have completed all review cards. This can be useful in scenarios where you have a mountain of new cards and only a minuscule number of reviews to compare against them. With the setting set to False, PB would show little to no progress as 10 or 20 reviews won't make a dent in the several thousand new cards PB is counting.

Thanks also for the reminder about the add-on configuration under 2.1. Adding a proper 2.1-compatible config is definitely on my to-do list.

In any case, hope that helps!
