### ISSUE TITLE
[Progress bar] My Issue 

### ISSUE THREAD

**Issue by hubble8** [glutanimate/progress-bar#3]
glutanimate/anki-addons-misc#44  Prerequisite checklist

[ Please enter an [ x ] character to confirm the points below: ]

- [x] In case of a bug: Have you tried restarting Anki?
- [x] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [x] Did you check the add-on description on AnkiWeb for known issues?
- [x] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

[ Recently forced to update my anki application to newest version. It would not let me open without it. As result I cannot use progress bar which is my absolute favorite add on. Would love an update. Willing to pay if necessary]

## Version information 2.1.35 

**Anki**

[ Version 2.1.34 ]

**System**

- Operating system: [ macOS ]
- Version: [ Catalina ]

**Comment by glutanimate** [comment]
Hey guys, thanks for the report and for helping out people while the fix wasn't merged, yet. Just chiming in to let you know that @liuzikai's fix is now merged into the development branch and will see a release with the upcoming version of the add-on. To track the progress of the release please see #5.
