### ISSUE TITLE
Compatibility Issue with Experimental Scheduler

### ISSUE THREAD

**Issue by jakelatino** [glutanimate/progress-bar#7]
## Which add-on is affected?

Progress Bar

## Prerequisite checklist

[ Please enter an [ x ] character to confirm the points below: ]

- [X ] In case of a bug: Have you tried restarting Anki?
- [X ] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [ X] Did you check the add-on description on AnkiWeb for known issues?
- [ X] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

I recently switched to the experimental scheduler, and it appears to have interfered with the mechanism by which Progress Bar calculates remaining cards. I would think it's related to the randomization of learning cards, perhaps?

## How can we reproduce the problem?

Switch to Anki 2.1 Scheduler (Windows 10)
Begin study (Progress bar will appear with moving bar across)
Study one card, says 100% completed

**Expected behavior:** [ What you expected to happen ]

Shows 100% completed, incorrectly.

**Actual behavior:** [ What actually happened ]

Falsely shows 100% completed

**Reproducible?:** [ Can you reliably reproduce the issue by following the steps above? ]

Unsure.

## Version information

2.1.22

**Comment by glutanimate** [comment]
Hey thanks for the report and apologies about the super late reply. This should be fixed in the current development branch, so I'm closing the issue for now. To follow along with the progress on the release, please see #5.
